/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-21 11:52:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminElements_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/kosmo_/Documents/GitHub/GivEngel-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GivEngel/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626740883918L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Lumino UI Elements</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/datepicker3.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--Custom Font-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("	<script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("	<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("	<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/adminElements.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/adminElements.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/adminElements.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/adminElements.jsp(29,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	\r\n");
          out.write("	");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/adminSidebar.jsp", out, false);
          out.write("\r\n");
          out.write("	<div id=\"sidebar-collapse\" class=\"col-sm-3 col-lg-2 sidebar\">\r\n");
          out.write("		<div class=\"profile-sidebar\">\r\n");
          out.write("			<div class=\"profile-userpic\">\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"profile-usertitle\">\r\n");
          out.write("				<div class=\"profile-usertitle-name\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("				<div class=\"profile-usertitle-status\"><span class=\"indicator label-success\"></span>Online</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"clear\"></div>\r\n");
          out.write("		</div>\r\n");
          out.write("		<div class=\"divider\"></div>\r\n");
          out.write("		<form role=\"search\">\r\n");
          out.write("			<div class=\"form-group\">\r\n");
          out.write("				<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
          out.write("			</div>\r\n");
          out.write("		</form>\r\n");
          out.write("		<ul class=\"nav menu\">\r\n");
          out.write("			<li><a href=\"adminMode.giv\"><em class=\"fa fa-dashboard\">&nbsp;</em> 누적통계</a></li>\r\n");
          out.write("			<li><a href=\"adminWidgets.giv\"><em class=\"fa fa-calendar\">&nbsp;</em> 개발자보드</a></li>\r\n");
          out.write("			<li ><a href=\"adminCharts.giv\"><em class=\"fa fa-bar-chart\">&nbsp;</em> 분석/통계</a></li>\r\n");
          out.write("			<li class=\"active\"><a href=\"adminElements.giv\"><em class=\"fa fa-toggle-off\">&nbsp;</em> 상품 추가</a></li>\r\n");
          out.write("			<li><a href=\"adminPanels.giv\"><em class=\"fa fa-clone\">&nbsp;</em> Alerts &amp; Panels</a></li>\r\n");
          out.write("			<li class=\"parent \"><a data-toggle=\"collapse\" href=\"#sub-item-1\">\r\n");
          out.write("				<em class=\"fa fa-navicon\">&nbsp;</em> Multilevel <span data-toggle=\"collapse\" href=\"#sub-item-1\" class=\"icon pull-right\"><em class=\"fa fa-plus\"></em></span>\r\n");
          out.write("				</a>\r\n");
          out.write("				<ul class=\"children collapse\" id=\"sub-item-1\">\r\n");
          out.write("					<li><a class=\"\" href=\"#\">\r\n");
          out.write("						<span class=\"fa fa-arrow-right\">&nbsp;</span> Sub Item 1\r\n");
          out.write("					</a></li>\r\n");
          out.write("					<li><a class=\"\" href=\"#\">\r\n");
          out.write("						<span class=\"fa fa-arrow-right\">&nbsp;</span> Sub Item 2\r\n");
          out.write("					</a></li>\r\n");
          out.write("					<li><a class=\"\" href=\"#\">\r\n");
          out.write("						<span class=\"fa fa-arrow-right\">&nbsp;</span> Sub Item 3\r\n");
          out.write("					</a></li>\r\n");
          out.write("				</ul>\r\n");
          out.write("			</li>\r\n");
          out.write("			<li><a href=\"adminlogoutAction.giv\"><em class=\"fa fa-power-off\">&nbsp;</em> 로그아웃</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</div>\r\n");
          out.write("	<!--/.sidebar-->\r\n");
          out.write("	<!-- ---------------------------------------------------------------------------------------- -->\r\n");
          out.write("\r\n");
          out.write("	<div class=\"col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main\">\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<ol class=\"breadcrumb\">\r\n");
          out.write("				<li><a href=\"#\"> <em class=\"fa fa-home\"></em>\r\n");
          out.write("				</a></li>\r\n");
          out.write("				<li class=\"active\">Forms</li>\r\n");
          out.write("			</ol>\r\n");
          out.write("		</div>\r\n");
          out.write("		<!--/.row-->\r\n");
          out.write("\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-lg-12\">\r\n");
          out.write("				<h1>상품 등록</h1>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("		<!--/.row-->\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-lg-12\">\r\n");
          out.write("\r\n");
          out.write("				<h2>최근 등록된 상품</h2>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div id=\"goodDiv\">\r\n");
          out.write("			\r\n");
          out.write("			</div>\r\n");
          out.write("			<!-- /.row -->\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("			<div class=\"panel panel-default\">\r\n");
          out.write("				\r\n");
          out.write("				<div class=\"panel-body\">\r\n");
          out.write("				<form id=\"insertfrm\" action=\"adminInsertGood.giv\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
          out.write("					<div class=\"col-md-6\">\r\n");
          out.write("						<input  name=\"url\" class=\"form-control\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  type=\"hidden\">\r\n");
          out.write("							<div class=\"form-group\">\r\n");
          out.write("								<label>상품명</label> <input id=\"good_name\" name=\"good_name\" class=\"form-control\" placeholder=\"상품명\">\r\n");
          out.write("							\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"form-group\">\r\n");
          out.write("								<label>상품가격</label> <input id=\"good_price\" name=\"good_price\" type=\"number\" class=\"form-control\"\r\n");
          out.write("									placeholder=\"상품 가격\">\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"form-group\">\r\n");
          out.write("								<label>상품재고</label> <input id=\"good_stock\" name=\"good_stock\" type=\"number\" class=\"form-control\"\r\n");
          out.write("									placeholder=\"상품 재고\">\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"form-group\">\r\n");
          out.write("								<label>등록 관리자</label> <input id=\"admin\" type=\"text\" name=\"admin\"\r\n");
          out.write("									value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin.admin_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"form-control\"\r\n");
          out.write("									disabled>\r\n");
          out.write("							</div>\r\n");
          out.write("\r\n");
          out.write("							<div class=\"form-group\">\r\n");
          out.write("								<label>파일 이미지</label> <input id=\"file\" name=\"file\" type=\"file\">\r\n");
          out.write("								<p class=\"help-block\">상품을 대표하는 이미지를 넣어주세요.</p>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"form-group\">\r\n");
          out.write("								<label>상품 설명</label>\r\n");
          out.write("								<textarea name=\"good_detail\" id=\"good_detail\" class=\"form-control\" rows=\"3\"></textarea>\r\n");
          out.write("							</div>\r\n");
          out.write("							<label>상품 태그 입력</label>\r\n");
          out.write("							<div class=\"form-group has-success\">\r\n");
          out.write("								<input type=\"text\" name=\"good_tags\" id=\"good_tags\" class=\"form-control\" placeholder=\"#태그특징\">\r\n");
          out.write("							</div>\r\n");
          out.write("					</div>\r\n");
          out.write("					<div class=\"col-md-6\">\r\n");
          out.write("						<div class=\"form-group\"></div>\r\n");
          out.write("						<div class=\"form-group\">\r\n");
          out.write("							<label>상품 카테고리</label>\r\n");
          out.write("							<div class=\"radio\">\r\n");
          out.write("								<label> <input type=\"radio\" name=\"good_tag\"\r\n");
          out.write("									id=\"optionsRadios1\" value=\"ACC\" checked>ACC\r\n");
          out.write("								</label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"radio\">\r\n");
          out.write("								<label> <input type=\"radio\" name=\"good_tag\"\r\n");
          out.write("									id=\"optionsRadios2\" value=\"TOP\">TOP\r\n");
          out.write("								</label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"radio\">\r\n");
          out.write("								<label> <input type=\"radio\" name=\"good_tag\"\r\n");
          out.write("									id=\"optionsRadios3\" value=\"BOTTOM\">BOTTOM\r\n");
          out.write("								</label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"radio\">\r\n");
          out.write("								<label> <input type=\"radio\" name=\"good_tag\"\r\n");
          out.write("									id=\"optionsRadios3\" value=\"BAG\">BAG\r\n");
          out.write("								</label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"radio\">\r\n");
          out.write("								<label> <input type=\"radio\" name=\"good_tag\"\r\n");
          out.write("									id=\"optionsRadios3\" value=\"SHOES\">SHOES\r\n");
          out.write("								</label>\r\n");
          out.write("							</div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"form-group\">\r\n");
          out.write("							<label>후원단체 등록</label> <select name=\"spon_no\" class=\"form-control\" id=\"selectSpon\">\r\n");
          out.write("								<option value=-1>none</option>\r\n");
          out.write("								\r\n");
          out.write("							</select>\r\n");
          out.write("						</div>\r\n");
          out.write("						\r\n");
          out.write("						<button id=\"submitbtn\" type=\"button\" class=\"btn btn-primary\">상품 등록하기</button>\r\n");
          out.write("						<button type=\"reset\" class=\"btn btn-default\">양식 초기화</button>\r\n");
          out.write("					</div>\r\n");
          out.write("					</form>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("		<!-- /.panel-->\r\n");
          out.write("	</div>\r\n");
          out.write("	<!-- /.col-->\r\n");
          out.write("	<div class=\"col-sm-12\">\r\n");
          out.write("		<p class=\"back-link\">\r\n");
          out.write("			Lumino Theme by <a href=\"https://www.medialoot.com\">Medialoot</a>\r\n");
          out.write("		</p>\r\n");
          out.write("	</div>\r\n");
          out.write("	</div>\r\n");
          out.write("	<!-- /.row -->\r\n");
          out.write("	</div>\r\n");
          out.write("	<!--/.main-->\r\n");
          out.write("\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/jquery-1.11.1.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/bootstrap.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/chart.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/chart-data.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/easypiechart.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/easypiechart-data.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/bootstrap-datepicker.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/custom.js\"></script>\r\n");
          out.write("	<script>\r\n");
          out.write("		window.onload = function() {\r\n");
          out.write("\r\n");
          out.write("			/* <div class=\"col-md-3\">\r\n");
          out.write("			<div class=\"panel panel-success\">\r\n");
          out.write("				<div class=\"panel-heading\">[상품명]</div>\r\n");
          out.write("				<div class=\"panel-body\">\r\n");
          out.write("					<p>[상품 디테일]</p>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			</div> */\r\n");
          out.write("			$.ajax({\r\n");
          out.write("				url : \"adminSelectSpon.giv\",\r\n");
          out.write("				type : \"post\",\r\n");
          out.write("				success : function(data) {\r\n");
          out.write("					var list = data.list;\r\n");
          out.write("					$(\"#selectSpon\").append(\"<option>none</option>\")\r\n");
          out.write("\r\n");
          out.write("					$(\"#selectSpon\").empty();\r\n");
          out.write("					for(var i=0;i<list.length;i++){\r\n");
          out.write("						$(\"#selectSpon\").append(\"<option value=\"+data.list[i].spon_no+\">\"+data.list[i].spon_name+\"</option>\")\r\n");
          out.write("						\r\n");
          out.write("				\r\n");
          out.write("					}\r\n");
          out.write("					\r\n");
          out.write("				}\r\n");
          out.write("			});\r\n");
          out.write("			\r\n");
          out.write("\r\n");
          out.write("			function updateGood() {\r\n");
          out.write("				$.ajax({\r\n");
          out.write("					url : \"adminSelectGood.giv\",\r\n");
          out.write("					type : \"post\",\r\n");
          out.write("					success : function(data) {\r\n");
          out.write("						var list = data.list;\r\n");
          out.write("\r\n");
          out.write("						$(\"#goodDiv\").empty();\r\n");
          out.write("						for(var i=0;i<4;i++){\r\n");
          out.write("							$(\"#goodDiv\").append('<div class=\"col-md-3\"><div class=\"panel panel-success\"><div class=\"panel-heading\">'+data.list[i].good_name+'</div><div class=\"panel-body\"><p>'+data.list[i].good_detail+'</p></div></div></div>')\r\n");
          out.write("						}\r\n");
          out.write("						\r\n");
          out.write("					}\r\n");
          out.write("				});\r\n");
          out.write("\r\n");
          out.write("			}\r\n");
          out.write("\r\n");
          out.write("			setInterval(updateGood, 2000);\r\n");
          out.write("			\r\n");
          out.write("			\r\n");
          out.write("			function checkform(){\r\n");
          out.write("				var good_name = $(\"#good_name\").val();\r\n");
          out.write("				var good_price = /[0-9]/;\r\n");
          out.write("				var good_stock = /[0-9]/;\r\n");
          out.write("				var admin = $(\"#admin\");\r\n");
          out.write("				var file = $(\"#file\").val();\r\n");
          out.write("				var good_detail = $(\"#good_detail\").val();\r\n");
          out.write("				var good_tags = $(\"#good_tags\").val();\r\n");
          out.write("				\r\n");
          out.write("				if(good_name==\"\"){\r\n");
          out.write("					alert(\"상품명을 입력해주세요\");\r\n");
          out.write("					return false;\r\n");
          out.write("				}\r\n");
          out.write("				if(!good_price.test($(\"#good_price\").val())){\r\n");
          out.write("					alert(\"상품 가격을 입력해주세요\");\r\n");
          out.write("					return false;\r\n");
          out.write("				}\r\n");
          out.write("				if(!good_stock.test($(\"#good_stock\").val())){\r\n");
          out.write("					alert(\"상품 재고를 입력해주세요\");\r\n");
          out.write("					return false;\r\n");
          out.write("				}\r\n");
          out.write("				if(admin==\"\"){\r\n");
          out.write("					alert(\"잘못된 접근입니다.\");\r\n");
          out.write("					return false;\r\n");
          out.write("				}\r\n");
          out.write("				if(good_detail==\"\"){\r\n");
          out.write("					alert(\" 상품 설명을 적어주세요\");\r\n");
          out.write("					return false;\r\n");
          out.write("				}\r\n");
          out.write("				if(good_tags==\"\"){\r\n");
          out.write("					alert(\"적어도 하나 이상의 태그를 입력해주세요\");\r\n");
          out.write("					return false;\r\n");
          out.write("				}\r\n");
          out.write("				\r\n");
          out.write("				return true;	\r\n");
          out.write("			}\r\n");
          out.write("			\r\n");
          out.write("			$(\"#submitbtn\").on(\"click\",function(){\r\n");
          out.write("				if(checkform()){\r\n");
          out.write("					alert(\"성공\");\r\n");
          out.write("					$(\"#insertfrm\").submit();\r\n");
          out.write("				}\r\n");
          out.write("			})\r\n");
          out.write("			\r\n");
          out.write("			\r\n");
          out.write("		}\r\n");
          out.write("	</script>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminElements.jsp(35,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv1.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminElements.jsp(38,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==2 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv2.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminElements.jsp(41,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==3 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv3.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminElements.jsp(44,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==4 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv4.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
