/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-19 06:36:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/KSC/Documents/GitHub/GivEngel-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GivEngel/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626234831845L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"Ogani Template\">\r\n");
      out.write("<meta name=\"keywords\" content=\"Ogani, unica, creative, html\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>살아숨쉬는 기부의 즐거움, GivEngel</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Css Styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/font-awesome.min.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/elegant-icons.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/nice-select.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/jquery-ui.min.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/owl.carousel.min.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slicknav.min.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mypage/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.15.3/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/myPage.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("	<!-- Page Preloder -->\r\n");
      out.write("	<div id=\"preloder\">\r\n");
      out.write("		<div class=\"loader\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark bg-primary fixed-top\" id=\"sideNav\">\r\n");
      out.write("            <a class=\"navbar-brand js-scroll-trigger\" href=\"index.giv\">\r\n");
      out.write("                <span class=\"d-block d-lg-none\">[유저 이름]</span>\r\n");
      out.write("                <span class=\"d-none d-lg-block\"><img class=\"img-fluid img-profile rounded-circle mx-auto mb-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mypage/logo.png\" alt=\"...\" /></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                <ul class=\"navbar-nav\">\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#about\">유저 정보(수정)</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#experience\">장바구니</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#education\">마일리지 사용내역</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#skills\">구매 내역</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#interests\">중고 장터 등록 상품</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#awards\">Givengel</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Page Content-->\r\n");
      out.write("        <div class=\"container-fluid p-0\">\r\n");
      out.write("            <!-- About-->\r\n");
      out.write("            <section class=\"resume-section\" id=\"about\">\r\n");
      out.write("                <div class=\"resume-section-content\">\r\n");
      out.write("                    <h1 class=\"mb-0\">\r\n");
      out.write("                        Welcome, \r\n");
      out.write("                        <span class=\"text-primary\">[유저이름]</span>\r\n");
      out.write("                    </h1>\r\n");
      out.write("                    <div class=\"subheading mb-5\">\r\n");
      out.write("                        [유저 아이디 수정 폼] \r\n");
      out.write("                        <a href=\"mailto:name@email.com\">name@email.com</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"lead mb-5\">I am experienced in leveraging agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition.</p>\r\n");
      out.write("                    <div class=\"social-icons\">\r\n");
      out.write("                        <a class=\"social-icon\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        <a class=\"social-icon\" href=\"#!\"><i class=\"fab fa-github\"></i></a>\r\n");
      out.write("                        <a class=\"social-icon\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"social-icon\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <hr class=\"m-0\" />\r\n");
      out.write("            <!-- Experience-->\r\n");
      out.write("            <section class=\"resume-section\" id=\"experience\">\r\n");
      out.write("                <div class=\"resume-section-content\">\r\n");
      out.write("                    <h2 class=\"mb-5\">장바구니[ajax 페이징처리]</h2>\r\n");
      out.write("                  <section class=\"shoping-cart spad\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"shoping__cart__table\">\r\n");
      out.write("						<table>\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th class=\"shoping__product\">담은 물품</th>\r\n");
      out.write("									<th>가격</th>\r\n");
      out.write("									<th>수량</th>\r\n");
      out.write("									<th>합계</th>\r\n");
      out.write("									<th></th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"shoping__cart__item\"><img\r\n");
      out.write("										src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/cart/cart-1.jpg\" alt=\"\">\r\n");
      out.write("										<h5>[물품1 이름]</h5></td>\r\n");
      out.write("									<td class=\"shoping__cart__price\">[물품 1 가격]</td>\r\n");
      out.write("									<td class=\"shoping__cart__quantity\">\r\n");
      out.write("										<div class=\"quantity\">\r\n");
      out.write("											<div class=\"pro-qty\">\r\n");
      out.write("												<input type=\"text\" value=\"1\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td class=\"shoping__cart__total\">[계산한 가격]</td>\r\n");
      out.write("									<td class=\"shoping__cart__item__close\"><span\r\n");
      out.write("										class=\"icon_close\"></span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"shoping__cart__item\"><img\r\n");
      out.write("										src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/cart/cart-1.jpg\" alt=\"\">\r\n");
      out.write("										<h5>[물품2 이름]</h5></td>\r\n");
      out.write("									<td class=\"shoping__cart__price\">[물품2 가격]</td>\r\n");
      out.write("									<td class=\"shoping__cart__quantity\">\r\n");
      out.write("										<div class=\"quantity\">\r\n");
      out.write("											<div class=\"pro-qty\">\r\n");
      out.write("												<input type=\"text\" value=\"1\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td class=\"shoping__cart__total\">[계산한 가격]</td>\r\n");
      out.write("									<td class=\"shoping__cart__item__close\"><span\r\n");
      out.write("										class=\"icon_close\"></span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"shoping__cart__item\"><img\r\n");
      out.write("										src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/cart/cart-1.jpg\" alt=\"\">\r\n");
      out.write("										<h5>[물품3 이름]</h5></td>\r\n");
      out.write("									<td class=\"shoping__cart__price\">[물품3 가격]</td>\r\n");
      out.write("									<td class=\"shoping__cart__quantity\">\r\n");
      out.write("										<div class=\"quantity\">\r\n");
      out.write("											<div class=\"pro-qty\">\r\n");
      out.write("												<input type=\"text\" value=\"1\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td class=\"shoping__cart__total\">[계산한 가격]</td>\r\n");
      out.write("									<td class=\"shoping__cart__item__close\"><span\r\n");
      out.write("										class=\"icon_close\"></span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"col-lg-6 \">\r\n");
      out.write("				<div class=\"shoping__cart__btns\">\r\n");
      out.write("						<a href=\"#\" class=\"primary-btn cart-btn\">쇼핑 계속하기</a> \r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6 \">\r\n");
      out.write("					<div class=\"shoping__checkout\">\r\n");
      out.write("						<h5>장바구니 전체 결제액</h5>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>총 가격 <span>[가격 계산]</span></li>\r\n");
      out.write("							<li>적립 마일리지 <span>[적립될 마일리지]</span></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<a href=\"#\" class=\"primary-btn\">구매하기</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <hr class=\"m-0\" />\r\n");
      out.write("            <!-- Education-->\r\n");
      out.write("            <section class=\"resume-section\" id=\"education\">\r\n");
      out.write("                <div class=\"resume-section-content\">\r\n");
      out.write("                    <h2 class=\"mb-5\">마일리지 사용내역[ajax 페이징 처리]</h2>\r\n");
      out.write("                    <div class=\"d-flex flex-column flex-md-row justify-content-between mb-5\">\r\n");
      out.write("                        <div class=\"flex-grow-1\">\r\n");
      out.write("                            <h3 class=\"mb-0\">[마일리지 내역 로그]</h3>\r\n");
      out.write("                            <div class=\"subheading mb-3\">[사용/얻은 마일리지]</div>\r\n");
      out.write("                            <div>[관련 후원단체]</div>\r\n");
      out.write("                            <p>[관련 캠페인]</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"flex-shrink-0\"><span class=\"text-primary\">[로그 날짜]</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex flex-column flex-md-row justify-content-between mb-5\">\r\n");
      out.write("                        <div class=\"flex-grow-1\">\r\n");
      out.write("                            <h3 class=\"mb-0\">[마일리지 내역 로그]</h3>\r\n");
      out.write("                            <div class=\"subheading mb-3\">[사용/얻은 마일리지]</div>\r\n");
      out.write("                            <div>[관련 후원단체]</div>\r\n");
      out.write("                            <p>[관련 캠페인]</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"flex-shrink-0\"><span class=\"text-primary\">[로그 날짜]</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <hr class=\"m-0\" />\r\n");
      out.write("            <!-- Skills-->\r\n");
      out.write("            <section class=\"resume-section\" id=\"skills\">\r\n");
      out.write("                <div class=\"resume-section-content\">\r\n");
      out.write("                    <h2 class=\"mb-5\">구매내역[ajax 페이징 처리]</h2>\r\n");
      out.write("                    <div class=\"d-flex flex-column flex-md-row justify-content-between mb-5\">\r\n");
      out.write("                        <div class=\"flex-grow-1\">\r\n");
      out.write("                            <h3 class=\"mb-0\">[구입한 물품]</h3>\r\n");
      out.write("                            <div class=\"subheading mb-3\">[사용한 금액]</div>\r\n");
      out.write("                            <div>[상품번호]</div>\r\n");
      out.write("                            <p>[구입한 개수 ]</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"flex-shrink-0\"><span class=\"text-primary\">[로그 날짜]</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <hr class=\"m-0\" />\r\n");
      out.write("            <!-- Interests-->\r\n");
      out.write("            <section class=\"resume-section\" id=\"interests\">\r\n");
      out.write("                <div class=\"resume-section-content\">\r\n");
      out.write("                    <h2 class=\"mb-5\">중고장터 등록상품</h2>\r\n");
      out.write("                    <div class=\"d-flex flex-column flex-md-row justify-content-between mb-5\">\r\n");
      out.write("                        <div class=\"flex-grow-1\">\r\n");
      out.write("                            <h3 class=\"mb-0\">[등록한 물품]</h3>\r\n");
      out.write("                            <div class=\"subheading mb-3\">[등록한 금액]</div>\r\n");
      out.write("                            <div>[중고상품번호]</div>\r\n");
      out.write("                            <p>[통과 여부 ]</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"flex-shrink-0\"><span class=\"text-primary\">[로그 날짜]</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <hr class=\"m-0\" />\r\n");
      out.write("            <!-- Awards-->\r\n");
      out.write("            <section class=\"resume-section\" id=\"awards\">\r\n");
      out.write("                <div class=\"resume-section-content\">\r\n");
      out.write("                    <h2 class=\"mb-5\">Awards & Certifications</h2>\r\n");
      out.write("                    <ul class=\"fa-ul mb-0\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"fa-li\"><i class=\"fas fa-trophy text-warning\"></i></span>\r\n");
      out.write("                            Google Analytics Certified Developer\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"fa-li\"><i class=\"fas fa-trophy text-warning\"></i></span>\r\n");
      out.write("                            Mobile Web Specialist - Google Certification\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"fa-li\"><i class=\"fas fa-trophy text-warning\"></i></span>\r\n");
      out.write("                            1\r\n");
      out.write("                            <sup>st</sup>\r\n");
      out.write("                            Place - University of Colorado Boulder - Emerging Tech Competition 2009\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"fa-li\"><i class=\"fas fa-trophy text-warning\"></i></span>\r\n");
      out.write("                            1\r\n");
      out.write("                            <sup>st</sup>\r\n");
      out.write("                            Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"fa-li\"><i class=\"fas fa-trophy text-warning\"></i></span>\r\n");
      out.write("                            2\r\n");
      out.write("                            <sup>nd</sup>\r\n");
      out.write("                            Place - University of Colorado Boulder - Emerging Tech Competition 2008\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"fa-li\"><i class=\"fas fa-trophy text-warning\"></i></span>\r\n");
      out.write("                            1\r\n");
      out.write("                            <sup>st</sup>\r\n");
      out.write("                            Place - James Buchanan High School - Hackathon 2006\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"fa-li\"><i class=\"fas fa-trophy text-warning\"></i></span>\r\n");
      out.write("                            3\r\n");
      out.write("                            <sup>rd</sup>\r\n");
      out.write("                            Place - James Buchanan High School - Hackathon 2005\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Section Begin -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Js Plugins -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/mixitup.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js_page/myPage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/myPage.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/myPage.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/myPage.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
