/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-21 08:00:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminMode_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/kosmo_/Documents/GitHub/GivEngel-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GivEngel/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626740883918L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<title>Lumino - Dashboard</title>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/datepicker3.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!--Custom Font-->\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("	<!--[if lt IE 9]>\r\n");
      out.write("	<script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("	<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("	<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/adminMode.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/adminMode.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/adminMode.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/adminMode.jsp(24,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	\r\n");
          out.write("	");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/adminSidebar.jsp", out, false);
          out.write("\r\n");
          out.write("	<div id=\"sidebar-collapse\" class=\"col-sm-3 col-lg-2 sidebar\">\r\n");
          out.write("		<div class=\"profile-sidebar\">\r\n");
          out.write("			<div class=\"profile-userpic\">\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"profile-usertitle\">\r\n");
          out.write("				<div class=\"profile-usertitle-name\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("				<div class=\"profile-usertitle-status\"><span class=\"indicator label-success\"></span>Online</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"clear\"></div>\r\n");
          out.write("		</div>\r\n");
          out.write("		<div class=\"divider\"></div>\r\n");
          out.write("		<form role=\"search\">\r\n");
          out.write("			<div class=\"form-group\">\r\n");
          out.write("				<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
          out.write("			</div>\r\n");
          out.write("		</form>\r\n");
          out.write("		<ul class=\"nav menu\">\r\n");
          out.write("			<li class=\"active\"><a href=\"adminMode.giv\"><em class=\"fa fa-dashboard\">&nbsp;</em> Dashboard</a></li>\r\n");
          out.write("			<li><a href=\"adminWidgets.giv\"><em class=\"fa fa-calendar\">&nbsp;</em> Widgets</a></li>\r\n");
          out.write("			<li ><a href=\"adminCharts.giv\"><em class=\"fa fa-bar-chart\">&nbsp;</em> Charts</a></li>\r\n");
          out.write("			<li><a href=\"adminElements.giv\"><em class=\"fa fa-toggle-off\">&nbsp;</em> UI Elements</a></li>\r\n");
          out.write("			<li><a href=\"adminPanels.giv\"><em class=\"fa fa-clone\">&nbsp;</em> Alerts &amp; Panels</a></li>\r\n");
          out.write("			<li class=\"parent \"><a data-toggle=\"collapse\" href=\"#sub-item-1\">\r\n");
          out.write("				<em class=\"fa fa-navicon\">&nbsp;</em> Multilevel <span data-toggle=\"collapse\" href=\"#sub-item-1\" class=\"icon pull-right\"><em class=\"fa fa-plus\"></em></span>\r\n");
          out.write("				</a>\r\n");
          out.write("				<ul class=\"children collapse\" id=\"sub-item-1\">\r\n");
          out.write("					<li><a class=\"\" href=\"#\">\r\n");
          out.write("						<span class=\"fa fa-arrow-right\">&nbsp;</span> Sub Item 1\r\n");
          out.write("					</a></li>\r\n");
          out.write("					<li><a class=\"\" href=\"#\">\r\n");
          out.write("						<span class=\"fa fa-arrow-right\">&nbsp;</span> Sub Item 2\r\n");
          out.write("					</a></li>\r\n");
          out.write("					<li><a class=\"\" href=\"#\">\r\n");
          out.write("						<span class=\"fa fa-arrow-right\">&nbsp;</span> Sub Item 3\r\n");
          out.write("					</a></li>\r\n");
          out.write("				</ul>\r\n");
          out.write("			</li>\r\n");
          out.write("			<li><a href=\"adminlogoutAction.giv\"><em class=\"fa fa-power-off\">&nbsp;</em> Logout</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</div>\r\n");
          out.write("	<!--/.sidebar-->\r\n");
          out.write("		\r\n");
          out.write("	<div class=\"col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main\">\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<ol class=\"breadcrumb\">\r\n");
          out.write("				<li><a href=\"#\">\r\n");
          out.write("					<em class=\"fa fa-home\"></em>\r\n");
          out.write("				</a></li>\r\n");
          out.write("				<li class=\"active\">Dashboard</li>\r\n");
          out.write("			</ol>\r\n");
          out.write("		</div><!--/.row-->\r\n");
          out.write("		\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-lg-12\">\r\n");
          out.write("				<h1 class=\"page-header\">누적 통계</h1>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div><!--/.row-->\r\n");
          out.write("		\r\n");
          out.write("		<div class=\"panel panel-container\">\r\n");
          out.write("			<div class=\"row\">\r\n");
          out.write("				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\r\n");
          out.write("					<div class=\"panel panel-teal panel-widget border-right\">\r\n");
          out.write("						<div class=\"row no-padding\"><em class=\"fa fa-xl fa-shopping-cart color-blue\"></em>\r\n");
          out.write("							<div class=\"large\"><span id=\"orderCount\"></span></div>\r\n");
          out.write("							<div class=\"text-muted\">총 주문</div>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\r\n");
          out.write("					<div class=\"panel panel-blue panel-widget border-right\">\r\n");
          out.write("						<div class=\"row no-padding\"><em class=\"fa fa-xl fa-comments color-orange\"></em>\r\n");
          out.write("							<div class=\"large\" ><span id=\"userCount\"></span></div>\r\n");
          out.write("							<div class=\"text-muted\" >총 유저</div>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\r\n");
          out.write("					<div class=\"panel panel-orange panel-widget border-right\">\r\n");
          out.write("						<div class=\"row no-padding\"><em class=\"fa fa-xl fa-users color-teal\"></em>\r\n");
          out.write("							<div class=\"large\"><span id=\"saleCount\"></span></div>\r\n");
          out.write("							<div class=\"text-muted\">총 구입금액</div>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\r\n");
          out.write("					<div class=\"panel panel-red panel-widget \">\r\n");
          out.write("						<div class=\"row no-padding\"><em class=\"fa fa-xl fa-search color-red\"></em>\r\n");
          out.write("							<div class=\"large\">25.2k</div>\r\n");
          out.write("							<div class=\"text-muted\">총 사용된 마일리지</div>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div><!--/.row-->\r\n");
          out.write("		</div>\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-md-12\">\r\n");
          out.write("				<div class=\"panel panel-default\">\r\n");
          out.write("					<div class=\"panel-heading\">\r\n");
          out.write("						사이트 접속 트래픽\r\n");
          out.write("						<ul class=\"pull-right panel-settings panel-button-tab-right\">\r\n");
          out.write("							<li class=\"dropdown\"><a class=\"pull-right dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
          out.write("								<em class=\"fa fa-cogs\"></em>\r\n");
          out.write("							</a>\r\n");
          out.write("								<ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("									<li>\r\n");
          out.write("										<ul class=\"dropdown-settings\">\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 1\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 2\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 3\r\n");
          out.write("											</a></li>\r\n");
          out.write("										</ul>\r\n");
          out.write("									</li>\r\n");
          out.write("								</ul>\r\n");
          out.write("							</li>\r\n");
          out.write("						</ul>\r\n");
          out.write("						<span class=\"pull-right clickable panel-toggle panel-button-tab-left\"><em class=\"fa fa-toggle-up\"></em></span></div>\r\n");
          out.write("					<div class=\"panel-body\">\r\n");
          out.write("						<div class=\"canvas-wrapper\">\r\n");
          out.write("							<canvas class=\"main-chart\" id=\"line-chart\" height=\"200\" width=\"600\"></canvas>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div><!--/.row-->\r\n");
          out.write("		\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-xs-6 col-md-3\">\r\n");
          out.write("				<div class=\"panel panel-default\">\r\n");
          out.write("					<div class=\"panel-body easypiechart-panel\">\r\n");
          out.write("						<h4>저번 달 비교 주문율</h4>\r\n");
          out.write("						<div class=\"easypiechart\" id=\"easypiechart-blue\" data-percent=\"92\" ><span class=\"percent\">92%</span></div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"col-xs-6 col-md-3\">\r\n");
          out.write("				<div class=\"panel panel-default\">\r\n");
          out.write("					<div class=\"panel-body easypiechart-panel\">\r\n");
          out.write("						<h4>저번 달 비교 신규 유저</h4>\r\n");
          out.write("						<div class=\"easypiechart\" id=\"easypiechart-orange\" data-percent=\"65\" ><span class=\"percent\">65%</span></div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"col-xs-6 col-md-3\">\r\n");
          out.write("				<div class=\"panel panel-default\">\r\n");
          out.write("					<div class=\"panel-body easypiechart-panel\">\r\n");
          out.write("						<h4>저번 달 비교 구입금액</h4>\r\n");
          out.write("						<div class=\"easypiechart\" id=\"easypiechart-teal\" data-percent=\"56\" ><span class=\"percent\">56%</span></div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"col-xs-6 col-md-3\">\r\n");
          out.write("				<div class=\"panel panel-default\">\r\n");
          out.write("					<div class=\"panel-body easypiechart-panel\">\r\n");
          out.write("						<h4>저번 달 비교 방문자</h4>\r\n");
          out.write("						<div class=\"easypiechart\" id=\"easypiechart-red\" data-percent=\"27\" ><span class=\"percent\">27%</span></div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div><!--/.row-->\r\n");
          out.write("		\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-md-6\">\r\n");
          out.write("				<div class=\"panel panel-default chat\">\r\n");
          out.write("					<div class=\"panel-heading\">\r\n");
          out.write("						DEV LOG\r\n");
          out.write("						<ul class=\"pull-right panel-settings panel-button-tab-right\">\r\n");
          out.write("							<li class=\"dropdown\"><a class=\"pull-right dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
          out.write("								<em class=\"fa fa-cogs\"></em>\r\n");
          out.write("							</a>\r\n");
          out.write("								<ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("									<li>\r\n");
          out.write("										<ul class=\"dropdown-settings\">\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 1\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 2\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 3\r\n");
          out.write("											</a></li>\r\n");
          out.write("										</ul>\r\n");
          out.write("									</li>\r\n");
          out.write("								</ul>\r\n");
          out.write("							</li>\r\n");
          out.write("						</ul>\r\n");
          out.write("						<span class=\"pull-right clickable panel-toggle panel-button-tab-left\"><em class=\"fa fa-toggle-up\"></em></span></div>\r\n");
          out.write("					<div class=\"panel-body\">\r\n");
          out.write("						<ul id=\"devLog\">\r\n");
          out.write("						\r\n");
          out.write("							\r\n");
          out.write("							\r\n");
          out.write("						</ul>\r\n");
          out.write("					</div>\r\n");
          out.write("					<div class=\"panel-footer\">\r\n");
          out.write("						<div class=\"input-group\">\r\n");
          out.write("							<input id=\"btn-input\" type=\"text\" class=\"form-control input-md\" placeholder=\"Type your message here...\" /><span class=\"input-group-btn\">\r\n");
          out.write("								<button class=\"btn btn-primary btn-md\" id=\"btn-chat\">Send</button>\r\n");
          out.write("						</span></div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"panel panel-default\">\r\n");
          out.write("					<div class=\"panel-heading\">\r\n");
          out.write("						해야할 것\r\n");
          out.write("						<ul class=\"pull-right panel-settings panel-button-tab-right\">\r\n");
          out.write("							<li class=\"dropdown\"><a class=\"pull-right dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
          out.write("								<em class=\"fa fa-cogs\"></em>\r\n");
          out.write("							</a>\r\n");
          out.write("								<ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("									<li>\r\n");
          out.write("										<ul class=\"dropdown-settings\">\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 1\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 2\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 3\r\n");
          out.write("											</a></li>\r\n");
          out.write("										</ul>\r\n");
          out.write("									</li>\r\n");
          out.write("								</ul>\r\n");
          out.write("							</li>\r\n");
          out.write("						</ul>\r\n");
          out.write("						<span class=\"pull-right clickable panel-toggle panel-button-tab-left\"><em class=\"fa fa-toggle-up\"></em></span></div>\r\n");
          out.write("					<div class=\"panel-body\">\r\n");
          out.write("						<ul class=\"todo-list\">\r\n");
          out.write("							<li class=\"todo-list-item\">\r\n");
          out.write("								<div class=\"checkbox\">\r\n");
          out.write("									<input type=\"checkbox\" id=\"checkbox-1\" />\r\n");
          out.write("									<label for=\"checkbox-1\">Make coffee</label>\r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"pull-right action-buttons\"><a href=\"#\" class=\"trash\">\r\n");
          out.write("									<em class=\"fa fa-trash\"></em>\r\n");
          out.write("								</a></div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li class=\"todo-list-item\">\r\n");
          out.write("								<div class=\"checkbox\">\r\n");
          out.write("									<input type=\"checkbox\" id=\"checkbox-2\" />\r\n");
          out.write("									<label for=\"checkbox-2\">Check emails</label>\r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"pull-right action-buttons\"><a href=\"#\" class=\"trash\">\r\n");
          out.write("									<em class=\"fa fa-trash\"></em>\r\n");
          out.write("								</a></div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li class=\"todo-list-item\">\r\n");
          out.write("								<div class=\"checkbox\">\r\n");
          out.write("									<input type=\"checkbox\" id=\"checkbox-3\" />\r\n");
          out.write("									<label for=\"checkbox-3\">Reply to Jane</label>\r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"pull-right action-buttons\"><a href=\"#\" class=\"trash\">\r\n");
          out.write("									<em class=\"fa fa-trash\"></em>\r\n");
          out.write("								</a></div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li class=\"todo-list-item\">\r\n");
          out.write("								<div class=\"checkbox\">\r\n");
          out.write("									<input type=\"checkbox\" id=\"checkbox-4\" />\r\n");
          out.write("									<label for=\"checkbox-4\">Make more coffee</label>\r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"pull-right action-buttons\"><a href=\"#\" class=\"trash\">\r\n");
          out.write("									<em class=\"fa fa-trash\"></em>\r\n");
          out.write("								</a></div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li class=\"todo-list-item\">\r\n");
          out.write("								<div class=\"checkbox\">\r\n");
          out.write("									<input type=\"checkbox\" id=\"checkbox-5\" />\r\n");
          out.write("									<label for=\"checkbox-5\">Work on the new design</label>\r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"pull-right action-buttons\"><a href=\"#\" class=\"trash\">\r\n");
          out.write("									<em class=\"fa fa-trash\"></em>\r\n");
          out.write("								</a></div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li class=\"todo-list-item\">\r\n");
          out.write("								<div class=\"checkbox\">\r\n");
          out.write("									<input type=\"checkbox\" id=\"checkbox-6\" />\r\n");
          out.write("									<label for=\"checkbox-6\">Get feedback on design</label>\r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"pull-right action-buttons\"><a href=\"#\" class=\"trash\">\r\n");
          out.write("									<em class=\"fa fa-trash\"></em>\r\n");
          out.write("								</a></div>\r\n");
          out.write("							</li>\r\n");
          out.write("						</ul>\r\n");
          out.write("					</div>\r\n");
          out.write("					<div class=\"panel-footer\">\r\n");
          out.write("						<div class=\"input-group\">\r\n");
          out.write("							<input id=\"btn-input\" type=\"text\" class=\"form-control input-md\" placeholder=\"Add new task\" /><span class=\"input-group-btn\">\r\n");
          out.write("								<button class=\"btn btn-primary btn-md\" id=\"btn-todo\">Add</button>\r\n");
          out.write("						</span></div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div><!--/.col-->\r\n");
          out.write("			\r\n");
          out.write("			\r\n");
          out.write("			<div class=\"col-md-6\">\r\n");
          out.write("				<div class=\"panel panel-default \">\r\n");
          out.write("					<div class=\"panel-heading\">\r\n");
          out.write("						USER LOG\r\n");
          out.write("						<ul class=\"pull-right panel-settings panel-button-tab-right\">\r\n");
          out.write("							<li class=\"dropdown\"><a class=\"pull-right dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
          out.write("								<em class=\"fa fa-cogs\"></em>\r\n");
          out.write("							</a>\r\n");
          out.write("								<ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("									<li>\r\n");
          out.write("										<ul class=\"dropdown-settings\">\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 1\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 2\r\n");
          out.write("											</a></li>\r\n");
          out.write("											<li class=\"divider\"></li>\r\n");
          out.write("											<li><a href=\"#\">\r\n");
          out.write("												<em class=\"fa fa-cog\"></em> Settings 3\r\n");
          out.write("											</a></li>\r\n");
          out.write("										</ul>\r\n");
          out.write("									</li>\r\n");
          out.write("								</ul>\r\n");
          out.write("							</li>\r\n");
          out.write("						</ul>\r\n");
          out.write("						<span class=\"pull-right clickable panel-toggle panel-button-tab-left\"><em class=\"fa fa-toggle-up\"></em></span></div>\r\n");
          out.write("					<div class=\"panel-body timeline-container\">\r\n");
          out.write("						<ul class=\"timeline\">\r\n");
          out.write("							<li>\r\n");
          out.write("								<div class=\"timeline-badge\"><em class=\"glyphicon glyphicon-pushpin\"></em></div>\r\n");
          out.write("								<div class=\"timeline-panel\">\r\n");
          out.write("									<div class=\"timeline-heading\">\r\n");
          out.write("										<h4 class=\"timeline-title\">Lorem ipsum dolor sit amet</h4>\r\n");
          out.write("									</div>\r\n");
          out.write("									<div class=\"timeline-body\">\r\n");
          out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at sodales nisl. Donec malesuada orci ornare risus finibus feugiat.</p>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li>\r\n");
          out.write("								<div class=\"timeline-badge primary\"><em class=\"glyphicon glyphicon-link\"></em></div>\r\n");
          out.write("								<div class=\"timeline-panel\">\r\n");
          out.write("									<div class=\"timeline-heading\">\r\n");
          out.write("										<h4 class=\"timeline-title\">Lorem ipsum dolor sit amet</h4>\r\n");
          out.write("									</div>\r\n");
          out.write("									<div class=\"timeline-body\">\r\n");
          out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li>\r\n");
          out.write("								<div class=\"timeline-badge\"><em class=\"glyphicon glyphicon-camera\"></em></div>\r\n");
          out.write("								<div class=\"timeline-panel\">\r\n");
          out.write("									<div class=\"timeline-heading\">\r\n");
          out.write("										<h4 class=\"timeline-title\">Lorem ipsum dolor sit amet</h4>\r\n");
          out.write("									</div>\r\n");
          out.write("									<div class=\"timeline-body\">\r\n");
          out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at sodales nisl. Donec malesuada orci ornare risus finibus feugiat.</p>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							</li>\r\n");
          out.write("							<li>\r\n");
          out.write("								<div class=\"timeline-badge\"><em class=\"glyphicon glyphicon-paperclip\"></em></div>\r\n");
          out.write("								<div class=\"timeline-panel\">\r\n");
          out.write("									<div class=\"timeline-heading\">\r\n");
          out.write("										<h4 class=\"timeline-title\">Lorem ipsum dolor sit amet</h4>\r\n");
          out.write("									</div>\r\n");
          out.write("									<div class=\"timeline-body\">\r\n");
          out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							</li>\r\n");
          out.write("						</ul>\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div><!--/.col-->\r\n");
          out.write("			<div class=\"col-sm-12\">\r\n");
          out.write("				<p class=\"back-link\">Lumino Theme by <a href=\"https://www.medialoot.com\">Medialoot</a></p>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div><!--/.row-->\r\n");
          out.write("	</div>	<!--/.main-->\r\n");
          out.write("	\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/jquery-1.11.1.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/bootstrap.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/chart.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/chart-data.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/easypiechart.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/easypiechart-data.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/bootstrap-datepicker.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/js/admin/custom.js\"></script>\r\n");
          out.write("	<script>\r\n");
          out.write("		window.onload = function () {\r\n");
          out.write("	var chart1 = document.getElementById(\"line-chart\").getContext(\"2d\");\r\n");
          out.write("	window.myLine = new Chart(chart1).Line(lineChartData, {\r\n");
          out.write("	responsive: true,\r\n");
          out.write("	scaleLineColor: \"rgba(0,0,0,.2)\",\r\n");
          out.write("	scaleGridLineColor: \"rgba(0,0,0,.05)\",\r\n");
          out.write("	scaleFontColor: \"#c5c7cc\"\r\n");
          out.write("	});\r\n");
          out.write("	\r\n");
          out.write("	alert(\"개발 시작\");\r\n");
          out.write("\r\n");
          out.write("	function updateUserCount(){\r\n");
          out.write("		$.ajax({\r\n");
          out.write("			url:\"adminUserCount.giv\",\r\n");
          out.write("			type:\"post\",\r\n");
          out.write("			success:function(data){\r\n");
          out.write("				$(\"#userCount\").text(data+\"명\");\r\n");
          out.write("			}\r\n");
          out.write("		});\r\n");
          out.write("		\r\n");
          out.write("	}\r\n");
          out.write("	function updateSaleCount(){\r\n");
          out.write("		$.ajax({\r\n");
          out.write("			url:\"countSale.giv\",\r\n");
          out.write("			type:\"post\",\r\n");
          out.write("			success:function(data){\r\n");
          out.write("				$(\"#saleCount\").text(data +\"원\");\r\n");
          out.write("			}\r\n");
          out.write("		});\r\n");
          out.write("		\r\n");
          out.write("	}\r\n");
          out.write("	function updatOrderCount(){\r\n");
          out.write("		$.ajax({\r\n");
          out.write("			url:\"countOrder.giv\",\r\n");
          out.write("			type:\"post\",\r\n");
          out.write("			success:function(data){\r\n");
          out.write("				$(\"#orderCount\").text(data +\"번\");\r\n");
          out.write("			}\r\n");
          out.write("		});\r\n");
          out.write("		\r\n");
          out.write("	}\r\n");
          out.write("	/* <li class=\"left clearfix\"><span class=\"chat-img pull-left\">\r\n");
          out.write("	<img src=\"http://placehold.it/60/30a5ff/fff\" alt=\"User Avatar\" class=\"img-circle\" />\r\n");
          out.write("	</span>\r\n");
          out.write("	<div class=\"chat-body clearfix\">\r\n");
          out.write("		<div class=\"header\"><strong class=\"primary-font\">John Doe</strong> <small class=\"text-muted\">32 mins ago</small></div>\r\n");
          out.write("		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ante turpis, rutrum ut ullamcorper sed, dapibus ac nunc.</p>\r\n");
          out.write("	</div>\r\n");
          out.write("</li> */\r\n");
          out.write("	function updateDevLog(){\r\n");
          out.write("	$.ajax({\r\n");
          out.write("		url:\"selectDevLog.giv\",\r\n");
          out.write("		type:\"post\",\r\n");
          out.write("		success:function(data){\r\n");
          out.write("			$('#devLog').empty();\r\n");
          out.write("			var list = data.devLog;\r\n");
          out.write("			for(var i=0;i<data.devLog.length;i++){\r\n");
          out.write("				$('#devLog').append('<li class=\"left clearfix\"><span class=\"chat-img pull-left\"><img src=\"http://placehold.it/60/30a5ff/fff\" alt=\"User Avatar\" class=\"img-circle\" /></span><div class=\"chat-body clearfix\"><div class=\"header\"><strong class=\"primary-font\">'+data.id[i]+'</strong> <small class=\"text-muted\">'+data.devLog[i].log_date+'</small></div><p>'+ data.devLog[i].log_detail  +'</p></div></li>')\r\n");
          out.write("			}\r\n");
          out.write("		}\r\n");
          out.write("	});\r\n");
          out.write("	\r\n");
          out.write("}\r\n");
          out.write("	\r\n");
          out.write("	\r\n");
          out.write("	\r\n");
          out.write("	setInterval(updateUserCount,2000);\r\n");
          out.write("	setInterval(updateSaleCount,2000);\r\n");
          out.write("	setInterval(updatOrderCount,2000);\r\n");
          out.write("	setInterval(updateDevLog,5000);\r\n");
          out.write("	\r\n");
          out.write("};\r\n");
          out.write("	</script>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminMode.jsp(30,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv1.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminMode.jsp(33,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==2 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv2.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminMode.jsp(36,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==3 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv3.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/adminMode.jsp(39,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.admin_level ==4 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/img/admin/lv4.png\" class=\"img-responsive\" alt=\"\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
